// examples/react-app/src/App.tsx
import PrimaryButton from './components/PrimaryButton';
import Card from './components/Card';
import './App.css';

export default function App() {
  return (
    <div className="app">
      <header className="app-header">
        <h1>Designer Mode — React Example</h1>
        <p>Press <kbd>Ctrl+Shift+D</kbd> to activate the inspector, then click any element.</p>
      </header>

      <main className="app-main">
        <Card title="Getting Started">
          <p>This is a demo app for Designer Mode. The inspector panel lets you click any element, inspect its styles, and send requests to your AI agent to apply changes.</p>
          <PrimaryButton onClick={() => alert('clicked!')}>Click Me</PrimaryButton>
        </Card>

        <Card title="Typography">
          <h2>Heading 2</h2>
          <h3>Heading 3</h3>
          <p>Regular paragraph text with <strong>bold</strong> and <em>italic</em> styling.</p>
          <a href="#" onClick={e => e.preventDefault()}>A link element</a>
        </Card>

        <Card title="Colours">
          <div className="color-swatches">
            <div className="swatch" style={{ background: '#037DD6' }} data-label="Primary" />
            <div className="swatch" style={{ background: '#0260b4' }} data-label="Primary Dark" />
            <div className="swatch" style={{ background: '#f6f8fa' }} data-label="Surface" />
            <div className="swatch" style={{ background: '#1e1e1e' }} data-label="Dark" />
          </div>
        </Card>
      </main>
    </div>
  );
}

// examples/vue-app/src/App.vue
<template>
  <div class="app">
    <header class="app-header">
      <h1>Designer Mode — Vue Example</h1>
      <p>Press <kbd>Ctrl+Shift+D</kbd> to activate the inspector, then click any element.</p>
    </header>

    <main class="app-main">
      <AppCard title="Buttons">
        <AppButton data-testid="primary-btn" @click="handleClick">Primary Button</AppButton>
        <AppButton variant="secondary" data-testid="secondary-btn">Secondary</AppButton>
      </AppCard>

      <AppCard title="Typography">
        <h2>Heading 2</h2>
        <p>Regular paragraph text with <strong>bold</strong> and <em>italic</em> styling.</p>
      </AppCard>
    </main>
  </div>
</template>

<script setup lang="ts">
import AppCard from './components/AppCard.vue';
import AppButton from './components/AppButton.vue';

function handleClick() {
  alert('Button clicked!');
}
</script>

<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f6f8fa; }

.app { min-height: 100vh; }

.app-header {
  background: #1e1e1e;
  color: #e0e0e0;
  padding: 24px 32px;
}

.app-header h1 { font-size: 20px; font-weight: 700; margin-bottom: 6px; }
.app-header p { font-size: 14px; color: #888; }
.app-header kbd { background: #333; border-radius: 4px; padding: 1px 5px; font-size: 12px; font-family: monospace; }

.app-main {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
  gap: 20px;
  padding: 32px;
  max-width: 1200px;
  margin: 0 auto;
}
</style>
